apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag }}"
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - containerPort: 80