apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odyssey-ingress
  annotations:
    # This annotation is important for GKE Ingress
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      # This rule sends API traffic to the backend
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: entitlements-service
            port:
              number: 80
      # This rule sends all other traffic to the frontend
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 80