apiVersion: v1
kind: Service
metadata:
  name: entitlements-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: entitlements-service