apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: entitlements-service-monitor
  # This label is important so Prometheus can find this monitor.
  labels:
    team: entitlements
spec:
  selector:
    matchLabels:
      app: entitlements-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
  namespaceSelector:
    matchNames:
    - default