apiVersion: v1
kind: Service
metadata:
  name: entitlements-service
  labels:
    app: entitlements-service
  # Add this annotation block
  annotations:
    cloud.google.com/backend-config: '{"default": "entitlements-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: entitlements-service