replicaCount: 2

image: # Backend image
  repository: australia-southeast1-docker.pkg.dev/odyssey123-1752491152/odyssey-repo/entitlements-service
  pullPolicy: Always
  tag: "latest"

  # --- Add this new section for the frontend ---
frontendImage:
  repository: australia-southeast1-docker.pkg.dev/odyssey123-1752491152/odyssey-repo/frontend-service
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

# Environment variables for the application
# These will be pulled from a Kubernetes Secret
env:
  secretName: spanner-credentials

# Probes to ensure the application is healthy
livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 45
  periodSeconds: 15

readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 15