name: Odyssey CI/CD to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: odyssey123 # ‼️ UPDATE this with your GCP Project ID
  GKE_CLUSTER: odyssey-cluster
  GKE_REGION: australia-southeast1
  GCR_IMAGE_PATH: gcr.io/${{ secrets.GCP_PROJECT_ID }}/entitlements-service

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    # Add 'id-token' with 'write' permission for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/your-gcp-project-number/locations/global/workloadIdentityPools/github-pool/providers/github-provider' # ‼️ UPDATE this
        service_account: 'odyssey-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com' # ‼️ UPDATE this

    - name: Set up GKE credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_REGION }}

    - name: Authenticate Docker to GCR
      run: |-
        gcloud auth configure-docker ${{ env.GKE_REGION }}-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |-
        docker build -t $GCR_IMAGE_PATH:${{ github.sha }} ./app
        docker push $GCR_IMAGE_PATH:${{ github.sha }}

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0' # Use a specific version of Helm

    - name: Deploy with Helm
      run: |-
        helm upgrade --install entitlements-service ./helm/entitlements-service \
          --set image.repository=$GCR_IMAGE_PATH \
          --set image.tag=${{ github.sha }}