name: Odyssey CI/CD to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: odyssey123
  GKE_CLUSTER: odyssey-cluster
  GKE_REGION: australia-southeast1
  # CORRECTED THIS LINE: Use env.PROJECT_ID
  GCR_IMAGE_PATH: gcr.io/${{ env.PROJECT_ID }}/entitlements-service

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/656106947192/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        # CORRECTED THIS LINE: Hardcoded the full service account email for clarity
        service_account: 'odyssey-sa@odyssey123.iam.gserviceaccount.com'

    - name: Set up GKE credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_REGION }}

    - name: Authenticate Docker to GCR
      run: |-
        # Note: GCR is being replaced by Artifact Registry, but this command works for both.
        gcloud auth configure-docker gcr.io

    - name: Build and Push Docker Image
      run: |-
        docker build -t $GCR_IMAGE_PATH:${{ github.sha }} ./app
        docker push $GCR_IMAGE_PATH:${{ github.sha }}

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'

    - name: Deploy with Helm
      run: |-
        helm upgrade --install entitlements-service ./helm/entitlements-service \
          --set image.repository=$GCR_IMAGE_PATH \
          --set image.tag=${{ github.sha }}